
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 29 14:34:12 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 29;
  public static final int Llave_c = 36;
  public static final int Op_booleano = 32;
  public static final int Llave_a = 35;
  public static final int If = 8;
  public static final int T_dato = 5;
  public static final int Default = 16;
  public static final int Set = 17;
  public static final int Puts = 18;
  public static final int Else = 9;
  public static final int Break = 15;
  public static final int Corchete_c = 38;
  public static final int Corchete_a = 37;
  public static final int Proc = 20;
  public static final int While = 11;
  public static final int Division = 26;
  public static final int Int = 6;
  public static final int Cadena = 7;
  public static final int Parentesis_c = 34;
  public static final int Dos_p = 41;
  public static final int Parentesis_a = 33;
  public static final int For = 12;
  public static final int P_coma = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 13;
  public static final int Linea = 2;
  public static final int Apuntador = 42;
  public static final int Comilla_simple = 4;
  public static final int Op_atribucion = 30;
  public static final int ERROR = 45;
  public static final int Do = 10;
  public static final int Op_logico = 28;
  public static final int Case = 14;
  public static final int Expr = 19;
  public static final int Incr = 21;
  public static final int Identificador = 43;
  public static final int Resta = 24;
  public static final int Identif_variable = 27;
  public static final int Multiplicacion = 25;
  public static final int Op_incremento = 31;
  public static final int Numero = 44;
  public static final int Suma = 23;
  public static final int Main = 39;
  public static final int Igual = 22;
  public static final int Comillas = 3;
}

